### ISSUE TITLE
Fix vulnerabilities in Jenkins

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-dyfi-response#27]
See the OWASP report on jenkins for directions on how to fix these.

**Comment by emartinez-usgs** [comment]
https://github.com/emartinez-usgs/httpd-php/pull/1

See latest Jenkins output report for verification.

**Comment by jmfee-usgs** [comment]
Looks reasonable, but I do not have merge permission on your fork

**Comment by emartinez-usgs** [comment]
Most vulnerabilities are resolved. Remaining vulnerability is false positive. Results are output with `htmlspecialchars` and are safe for rendering.
