### ISSUE TITLE
Provide pertinent links on Submission Confirmation page

### ISSUE THREAD

**Issue by lisa-usgs** [usgs/earthquake-dyfi-response#7]
Such as:

Direct link for visitors to add to social media - "My DYFI intensity was <mmi here>. Did you feel it? (with link)

Preparedness info link

Education link(s)

Discussion with DYFI group and Lisa is needed to determine what links to add.

**Comment by llastowka-usgs** [comment]
Moved to https://github.com/usgs/earthquake-eventpages/issues/956
